apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  annotations:
    plugins.kubegems.io/category: core/KubeGems
    plugins.kubegems.io/description: KubeGems PAI components
  name: kubegems-pai
  namespace: kubegems-installer
spec:
  chart: kubegems-pai
  installNamespace: kubegems-pai
  kind: helm
  url: https://charts.kubegems.io/kubegems
  version: 1.0.8
  values:
    api:
      enabled: true
      image:
        tag: v1.0.8
    controller:
      enabled: true
      image:
        tag: v1.0.8
      ingress:
        baseHost: xpai.xiaoshiai.cn:30000
        className: default-gateway
      s3:
        accessKey: minioadmin
        addr: http://xpai-minio.kubegems-pai:9000
        bucket: ""
        capacity: 1024Gi
        pathStyle: true
        secretKey: minioadmin
      volcano:
        enabled: true
        vgpu:
          enabled: true
    node:
      enabled: true
      image:
        tag: v1.0.8
  valuesFrom:
  - kind: ConfigMap
    name: kubegems-global-values
    optional: true
    prefix: global.
