---
- name: Ensure URLs are downloaded, permissions set, and installed
  hosts: test
  vars:
    files:
      - name: Ascend-hdk-910b-npu-driver_24.1.rc1_linux-aarch64.run
        url: https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Ascend%20HDK/Ascend%20HDK%2024.1.RC1/Ascend-hdk-910b-npu-driver_24.1.rc1_linux-aarch64.run
      - name: Ascend-hdk-910b-npu-firmware_7.1.0.6.220.run
        url: https://ascend-repo.obs.cn-east-2.myhuaweicloud.com/Ascend%20HDK/Ascend%20HDK%2024.1.RC1/Ascend-hdk-910b-npu-firmware_7.1.0.6.220.run

  tasks:
    - name: Process each file
      include_tasks: sub-task.yaml
      loop: "{{ files }}"
      loop_control:
        loop_var: item
