apiVersion: v1
kind: ServiceAccount
metadata:
  name: noded
  namespace: mindx-dl
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-noded-role
rules:
  - apiGroups: [""]
    resources: ["nodes/status"]
    verbs: ["patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-noded-rolebinding
subjects:
  - kind: ServiceAccount
    name: noded
    namespace: mindx-dl
roleRef:
  kind: ClusterRole
  name: pods-noded-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: noded
  namespace: mindx-dl
spec:
  selector:
    matchLabels:
      app: noded
  template:
    metadata:
      labels:
        app: noded
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      nodeSelector:
        workerselector: dls-worker-node
      serviceAccountName: noded
      containers:
        - name: noded
          image: noded:v5.0.0.5
          resources:
            requests:
              memory: 300Mi
              cpu: 500m
            limits:
              memory: 300Mi
              cpu: 500m
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: Never
          command: [ "/bin/bash", "-c", "--"]
          args: [ "/home/hwMindX/noded -logFile=/var/log/mindx-dl/noded/noded.log -logLevel=0" ]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ "ALL" ]
            runAsUser: 9000
            runAsGroup: 9000
          volumeMounts:
            - name: log-noded
              mountPath: /var/log/mindx-dl/noded
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: log-noded
          hostPath:
            path: /var/log/mindx-dl/noded
            type: Directory
        - name: localtime
          hostPath:
            path: /etc/localtime